/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Recetarios_menus;

import Ventas_Compras_facturas.*;
import com.mysql.jdbc.Connection;
import conexion.BaseDeDatos;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alicer
 */
public class N_Receta_Ingr extends javax.swing.JFrame {

    int ID_ARTICULO = 0;
    String NOMBRE_ARTICULO = null;

    public void tabla() {
        DefaultTableModel modelo = new DefaultTableModel();
        jtProductos.setModel(modelo);
        modelo.addColumn("id.");
        modelo.addColumn("Nombre");
        modelo.addColumn("cantidad");
      
        
    }

    public void popuptable() {
        JPopupMenu popmenu = new JPopupMenu();
        JMenuItem menuitem = new JMenuItem("Eliminar", new ImageIcon(getClass().getResource("/iconos/eli.png")));
        menuitem.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                DefaultTableModel model = (DefaultTableModel) jtProductos.getModel();
                int a = jtProductos.getSelectedRow();
                if (a < 0) {
                    JOptionPane.showMessageDialog(null,
                            "Debe seleccionar una fila de la tabla");
                } else {
                    int confirmar = JOptionPane.showConfirmDialog(null,
                            "Esta seguro que desea quitar el producto? ");
                    if (JOptionPane.OK_OPTION == confirmar) {
                        model.removeRow(a);
                        JOptionPane.showMessageDialog(null, "Registro Eliminado");
                    }
                }
            }
        });

        popmenu.add(menuitem);

        jtProductos.setComponentPopupMenu(popmenu);
    }

    /**
     * Creates new form Factura_ingreso
     */
    public N_Receta_Ingr() {
        initComponents();
        tabla();
        popuptable();

        try {
            PreparedStatement ps = null;
            ResultSet rs = null;
            BaseDeDatos cone = new BaseDeDatos();
            com.mysql.jdbc.Connection conn = (com.mysql.jdbc.Connection) cone.conectar();
            DefaultTableModel modelo2 = new DefaultTableModel();
            jtArticulos.setModel(modelo2);

            String sql = "select id, nombre, stock, costo from materiaprima ";
            ps = conn.prepareStatement(sql);
            rs = ps.executeQuery();

            ResultSetMetaData rsMd = (ResultSetMetaData) rs.getMetaData();
            int cantidadColumnas = rsMd.getColumnCount();

            modelo2.addColumn("id.");
            modelo2.addColumn("Nombre");
            modelo2.addColumn("Existencia");
            modelo2.addColumn("Costo");

            int[] anchos = {10, 30, 70, 70};
            for (int i = 0; i < jtArticulos.getColumnCount(); i++) {
                jtArticulos.getColumnModel().getColumn(i).setPreferredWidth(anchos[i]);
            }

            while (rs.next()) {
                Object[] filas = new Object[cantidadColumnas];
                for (int i = 0; i < cantidadColumnas; i++) {
                    filas[i] = rs.getObject(i + 1);
                }
                modelo2.addRow(filas);
            }

            String corrArticulo = "Select nombre from receta order by(id)";
            ps = conn.prepareStatement(corrArticulo);
            rs = ps.executeQuery();

            while (rs.next()) {
                this.jcReceta.addItem(rs.getString("nombre"));
            }

        } catch (SQLException ex) {
            System.err.println(ex.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jcReceta = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtProductos = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtArticulos = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Detalles de la Factura", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Receta :");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 70, 98, 31));

        jPanel2.add(jcReceta, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 70, 266, 28));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 28, 1078, 126));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtProductos);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(518, 14, 658, 266));

        jtArticulos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtArticulos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtArticulosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtArticulos);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 14, 476, 266));

        jButton2.setText("Guardar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(784, 294, 112, 42));

        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 294, 112, 42));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 210, 1190, 350));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1268, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
//
        try {
            BaseDeDatos cone = new BaseDeDatos();
            com.mysql.jdbc.Connection conn = (com.mysql.jdbc.Connection) cone.conectar();
            PreparedStatement ps = null;
            

            int filas = jtProductos.getRowCount();
            System.out.println("filas jc " + filas);
            for (int row = 0; row < filas; row++) {
                ps = conn.prepareStatement("INSERT INTO `receta_ingrediente` (`receta_id`, `materiaprima_id`, `cantidad`) VALUES (?,?,?)");
                int id_receta = (int) jcReceta.getSelectedIndex() + 1;
                int id_materia = (int) jtProductos.getValueAt(row, 0);
                int cant = (int) jtProductos.getValueAt(row, 2);

                ps.setInt(1, id_receta);
                ps.setInt(2, id_materia);
                ps.setInt(3, cant);
                ps.execute();
                System.out.println("ya, asdfasdf");
            }
            JOptionPane.showMessageDialog(null, "Ingresado Correctamente");
            tabla();
            limpiar();
        } catch (SQLException ex) {
        }


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jtArticulosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtArticulosMouseClicked

        int Fila = jtArticulos.getSelectedRow();
        String codigo = jtArticulos.getValueAt(Fila, 0).toString();
        String nombre = jtArticulos.getValueAt(Fila, 1).toString();
        ID_ARTICULO = Integer.parseInt(codigo);
        NOMBRE_ARTICULO = nombre;
        System.out.println("id " + ID_ARTICULO);
        System.out.println("Nombre: " + NOMBRE_ARTICULO);
    }//GEN-LAST:event_jtArticulosMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String cant = JOptionPane.showInputDialog(null, "Ingrese la cantidad", JOptionPane.WARNING_MESSAGE);
        int cantidad = Integer.parseInt(cant);
        DefaultTableModel modelo = (DefaultTableModel) jtProductos.getModel();
        Object[] fila = new Object[5];
        fila[0] = ID_ARTICULO;
        fila[1] = NOMBRE_ARTICULO;
        fila[2] = cantidad;
        modelo.addRow(fila);
//        jtProductos.setModel(modelo);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void limpiar() {

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(N_Receta_Ingr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(N_Receta_Ingr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(N_Receta_Ingr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(N_Receta_Ingr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new N_Receta_Ingr().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> jcReceta;
    private javax.swing.JTable jtArticulos;
    private javax.swing.JTable jtProductos;
    // End of variables declaration//GEN-END:variables
}
