/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Freddy Camposeco <freddy.camposeco@elementum69.com>
 * <www.elementum69.com>
 */
public class MainMenu_ extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu_
     */
    public MainMenu_() {
        try { 
            UIManager.setLookAndFeel("com.alee.laf.WebLookAndFeel"); 
//            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch(ClassNotFoundException | IllegalAccessException | InstantiationException | UnsupportedLookAndFeelException ignored){}
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_MenuBar_ = new javax.swing.JPanel();
        jPanel_Main_ = new javax.swing.JPanel();
        jPanel_StatusBar_ = new javax.swing.JPanel();
        jPanel_Content_ = new javax.swing.JPanel();
        jTabbedPane_Content_ = new javax.swing.JTabbedPane();
        jPanel_Achivos_ = new javax.swing.JPanel();

        jPanel_MenuBar_.setBackground(new java.awt.Color(102, 0, 0));
        jPanel_MenuBar_.setMaximumSize(null);
        jPanel_MenuBar_.setMinimumSize(new java.awt.Dimension(200, 640));
        jPanel_MenuBar_.setName("MenuBar"); // NOI18N
        jPanel_MenuBar_.setPreferredSize(new java.awt.Dimension(200, 640));

        javax.swing.GroupLayout jPanel_MenuBar_Layout = new javax.swing.GroupLayout(jPanel_MenuBar_);
        jPanel_MenuBar_.setLayout(jPanel_MenuBar_Layout);
        jPanel_MenuBar_Layout.setHorizontalGroup(
            jPanel_MenuBar_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        jPanel_MenuBar_Layout.setVerticalGroup(
            jPanel_MenuBar_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(null);
        setMinimumSize(new java.awt.Dimension(1024, 661));
        setSize(new java.awt.Dimension(1024, 661));

        jPanel_Main_.setMinimumSize(new java.awt.Dimension(1024, 661));
        jPanel_Main_.setName(""); // NOI18N
        jPanel_Main_.setPreferredSize(new java.awt.Dimension(1024, 661));
        jPanel_Main_.setLayout(new java.awt.BorderLayout());

        jPanel_StatusBar_.setMaximumSize(null);
        jPanel_StatusBar_.setMinimumSize(new java.awt.Dimension(1024, 21));
        jPanel_StatusBar_.setPreferredSize(new java.awt.Dimension(1024, 21));

        javax.swing.GroupLayout jPanel_StatusBar_Layout = new javax.swing.GroupLayout(jPanel_StatusBar_);
        jPanel_StatusBar_.setLayout(jPanel_StatusBar_Layout);
        jPanel_StatusBar_Layout.setHorizontalGroup(
            jPanel_StatusBar_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1024, Short.MAX_VALUE)
        );
        jPanel_StatusBar_Layout.setVerticalGroup(
            jPanel_StatusBar_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );

        jPanel_Main_.add(jPanel_StatusBar_, java.awt.BorderLayout.SOUTH);

        jPanel_Content_.setMinimumSize(new java.awt.Dimension(824, 640));
        jPanel_Content_.setLayout(new java.awt.BorderLayout());

        jTabbedPane_Content_.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane_Content_.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel_Achivos_Layout = new javax.swing.GroupLayout(jPanel_Achivos_);
        jPanel_Achivos_.setLayout(jPanel_Achivos_Layout);
        jPanel_Achivos_Layout.setHorizontalGroup(
            jPanel_Achivos_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 933, Short.MAX_VALUE)
        );
        jPanel_Achivos_Layout.setVerticalGroup(
            jPanel_Achivos_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 635, Short.MAX_VALUE)
        );

        jTabbedPane_Content_.addTab("1234567890", jPanel_Achivos_);

        jTabbedPane_Content_.setSelectedComponent(jPanel_Achivos_);

        jPanel_Content_.add(jTabbedPane_Content_, java.awt.BorderLayout.CENTER);

        jPanel_Main_.add(jPanel_Content_, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel_Main_, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu_.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu_.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu_.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu_.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu_().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel_Achivos_;
    private javax.swing.JPanel jPanel_Content_;
    private javax.swing.JPanel jPanel_Main_;
    private javax.swing.JPanel jPanel_MenuBar_;
    private javax.swing.JPanel jPanel_StatusBar_;
    private javax.swing.JTabbedPane jTabbedPane_Content_;
    // End of variables declaration//GEN-END:variables
}
