/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Timer;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Freddy Camposeco <freddy.camposeco@elementum69.com>
 * <www.elementum69.com>
 */
public class MainMenu extends javax.swing.JFrame {
    private static final String SAMS = " Sam's ";
    
    private Boolean switchMenuBar = false;
    private Boolean switchMenu = false;
    
    
    private void ocultarMenuBar (){
        if (switchMenuBar == false){
            jMenuBar_.setVisible(true);
            switchMenuBar = true;
        } else if (switchMenuBar == true){
            jMenuBar_.setVisible(false);
            switchMenuBar = false;
        } else {
            System.err.println("Error al ocultar Barra de Menú");
        }
    }
    
    private void mostrarMenu (){
        if (switchMenu == true){
            jPanel_Main_.remove(jPanel_MenuBar_);
            jPanel_Main_.add(jPanel_MenuBar_, java.awt.BorderLayout.WEST);
            jLabel_MostrarMenu_.setText("Ocultar");
            switchMenu = false;
        }
        else if (switchMenu == false) {
            jPanel_Main_.remove(jPanel_MenuBarSmall_);
            jPanel_Main_.add(jPanel_MenuBarSmall_, java.awt.BorderLayout.WEST);
            jLabel_MostrarMenu_.setText("Mostrar");
            switchMenu = true;
        }
        else {
            System.err.println("Error al mostrar el menu");
        }
    }
    
    public MainMenu() {
        try { 
            UIManager.setLookAndFeel("com.alee.laf.WebLookAndFeel"); 
//            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch(ClassNotFoundException | IllegalAccessException | InstantiationException | UnsupportedLookAndFeelException ignored){}
        initComponents();
        jMenuBar_.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_MenuBarSmall_ = new javax.swing.JPanel();
        jPanel_Main_ = new javax.swing.JPanel();
        jPanel_StatusBar_ = new javax.swing.JPanel();
        jLabel_HORA_ = new javax.swing.JLabel();
        jLabel_MostrarMenu_ = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel_Content_ = new javax.swing.JPanel();
        jTabbedPane_Content_ = new javax.swing.JTabbedPane();
        jPanel_Achivos_ = new javax.swing.JPanel();
        jPanel_MenuBar_ = new javax.swing.JPanel();
        jMenuBar_ = new javax.swing.JMenuBar();
        jMenu_Archivos_ = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem_Salir_ = new javax.swing.JMenuItem();
        jMenu_Help_ = new javax.swing.JMenu();
        jMenuItem_Help_ = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        jPanel_MenuBarSmall_.setBackground(java.awt.Color.darkGray);
        jPanel_MenuBarSmall_.setForeground(java.awt.Color.white);
        jPanel_MenuBarSmall_.setMaximumSize(null);
        jPanel_MenuBarSmall_.setMinimumSize(new java.awt.Dimension(32, 640));
        jPanel_MenuBarSmall_.setName("MenuBar"); // NOI18N
        jPanel_MenuBarSmall_.setPreferredSize(new java.awt.Dimension(32, 640));

        javax.swing.GroupLayout jPanel_MenuBarSmall_Layout = new javax.swing.GroupLayout(jPanel_MenuBarSmall_);
        jPanel_MenuBarSmall_.setLayout(jPanel_MenuBarSmall_Layout);
        jPanel_MenuBarSmall_Layout.setHorizontalGroup(
            jPanel_MenuBarSmall_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );
        jPanel_MenuBarSmall_Layout.setVerticalGroup(
            jPanel_MenuBarSmall_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(null);
        setMinimumSize(new java.awt.Dimension(1024, 661));
        setSize(new java.awt.Dimension(1024, 661));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel_Main_.setMinimumSize(new java.awt.Dimension(1024, 661));
        jPanel_Main_.setName(""); // NOI18N
        jPanel_Main_.setPreferredSize(new java.awt.Dimension(1024, 661));
        jPanel_Main_.setLayout(new java.awt.BorderLayout());

        jPanel_StatusBar_.setBackground(java.awt.Color.darkGray);
        jPanel_StatusBar_.setForeground(java.awt.Color.white);
        jPanel_StatusBar_.setMaximumSize(null);
        jPanel_StatusBar_.setMinimumSize(new java.awt.Dimension(1024, 21));
        jPanel_StatusBar_.setPreferredSize(new java.awt.Dimension(1024, 21));

        jLabel_HORA_.setBackground(java.awt.Color.darkGray);
        jLabel_HORA_.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_HORA_.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_HORA_.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_HORA_.setText("| 2019-01-01 | dom | 00:00:00 AM |");

        jLabel_MostrarMenu_.setBackground(java.awt.Color.darkGray);
        jLabel_MostrarMenu_.setForeground(java.awt.Color.white);
        jLabel_MostrarMenu_.setText("Ocultar");
        jLabel_MostrarMenu_.setMaximumSize(new java.awt.Dimension(21, 21));
        jLabel_MostrarMenu_.setMinimumSize(new java.awt.Dimension(21, 21));
        jLabel_MostrarMenu_.setPreferredSize(new java.awt.Dimension(34, 21));
        jLabel_MostrarMenu_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_MostrarMenu_MouseClicked(evt);
            }
        });

        jLabel1.setBackground(java.awt.Color.darkGray);
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/core/resources/icons/ResizeCornerW0X16.gif"))); // NOI18N
        jLabel1.setMaximumSize(null);
        jLabel1.setPreferredSize(new java.awt.Dimension(21, 21));

        javax.swing.GroupLayout jPanel_StatusBar_Layout = new javax.swing.GroupLayout(jPanel_StatusBar_);
        jPanel_StatusBar_.setLayout(jPanel_StatusBar_Layout);
        jPanel_StatusBar_Layout.setHorizontalGroup(
            jPanel_StatusBar_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_StatusBar_Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_MostrarMenu_, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 741, Short.MAX_VALUE)
                .addComponent(jLabel_HORA_)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel_StatusBar_Layout.setVerticalGroup(
            jPanel_StatusBar_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_StatusBar_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel_HORA_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_MostrarMenu_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel_Main_.add(jPanel_StatusBar_, java.awt.BorderLayout.SOUTH);

        jPanel_Content_.setMinimumSize(new java.awt.Dimension(824, 640));
        jPanel_Content_.setLayout(new java.awt.BorderLayout());

        jTabbedPane_Content_.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane_Content_.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel_Achivos_Layout = new javax.swing.GroupLayout(jPanel_Achivos_);
        jPanel_Achivos_.setLayout(jPanel_Achivos_Layout);
        jPanel_Achivos_Layout.setHorizontalGroup(
            jPanel_Achivos_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 733, Short.MAX_VALUE)
        );
        jPanel_Achivos_Layout.setVerticalGroup(
            jPanel_Achivos_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jTabbedPane_Content_.addTab("1234567890", jPanel_Achivos_);

        jTabbedPane_Content_.setSelectedComponent(jPanel_Achivos_);

        jPanel_Content_.add(jTabbedPane_Content_, java.awt.BorderLayout.CENTER);

        jPanel_Main_.add(jPanel_Content_, java.awt.BorderLayout.CENTER);

        jPanel_MenuBar_.setBackground(java.awt.Color.darkGray);
        jPanel_MenuBar_.setForeground(java.awt.Color.white);
        jPanel_MenuBar_.setMaximumSize(null);
        jPanel_MenuBar_.setMinimumSize(new java.awt.Dimension(200, 640));
        jPanel_MenuBar_.setName("MenuBar"); // NOI18N
        jPanel_MenuBar_.setPreferredSize(new java.awt.Dimension(200, 640));

        javax.swing.GroupLayout jPanel_MenuBar_Layout = new javax.swing.GroupLayout(jPanel_MenuBar_);
        jPanel_MenuBar_.setLayout(jPanel_MenuBar_Layout);
        jPanel_MenuBar_Layout.setHorizontalGroup(
            jPanel_MenuBar_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        jPanel_MenuBar_Layout.setVerticalGroup(
            jPanel_MenuBar_Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );

        jPanel_Main_.add(jPanel_MenuBar_, java.awt.BorderLayout.WEST);

        getContentPane().add(jPanel_Main_, java.awt.BorderLayout.CENTER);

        jMenu_Archivos_.setText("Archivo");
        jMenu_Archivos_.add(jSeparator1);

        jMenuItem_Salir_.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem_Salir_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/core/resources/icons/Exit0X24.png"))); // NOI18N
        jMenuItem_Salir_.setText("Salir");
        jMenuItem_Salir_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_Salir_ActionPerformed(evt);
            }
        });
        jMenu_Archivos_.add(jMenuItem_Salir_);

        jMenuBar_.add(jMenu_Archivos_);

        jMenu_Help_.setText("Ayuda");

        jMenuItem_Help_.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jMenuItem_Help_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/core/resources/icons/help0X24.png"))); // NOI18N
        jMenuItem_Help_.setText("Ayuda");
        jMenu_Help_.add(jMenuItem_Help_);

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/core/resources/icons/heartX24.png"))); // NOI18N
        jMenuItem1.setText("Acerca de ..");
        jMenu_Help_.add(jMenuItem1);

        jMenuBar_.add(jMenu_Help_);

        setJMenuBar(jMenuBar_);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        Timer tiempo = new Timer(100, new gui.MainMenu.hora());
        tiempo.start();
    }//GEN-LAST:event_formWindowOpened

    private void jLabel_MostrarMenu_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_MostrarMenu_MouseClicked
        mostrarMenu();
        
    }//GEN-LAST:event_jLabel_MostrarMenu_MouseClicked

    private void jMenuItem_Salir_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_Salir_ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem_Salir_ActionPerformed

    class hora implements ActionListener {
        @Override
        public void actionPerformed(ActionEvent e) {
            Date date = new Date();
            DateFormat inFormat = new SimpleDateFormat( "| dd-MM-yyyy | E | hh:mm:ss aa |");
            DateFormat outFormat = new SimpleDateFormat( "| yyyy-MM-dd | E | HH:mm:ss | ");
            
            String myDate = outFormat.format(date);
            setTitle(SAMS);
            jLabel_HORA_.setText(outFormat.format(date));
//            jLabel_HORA_.setForeground(new java.awt.Color(255, 0, 255));
        }
    }

    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(() -> {
            new MainMenu().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_HORA_;
    private javax.swing.JLabel jLabel_MostrarMenu_;
    private javax.swing.JMenuBar jMenuBar_;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem_Help_;
    private javax.swing.JMenuItem jMenuItem_Salir_;
    private javax.swing.JMenu jMenu_Archivos_;
    private javax.swing.JMenu jMenu_Help_;
    private javax.swing.JPanel jPanel_Achivos_;
    private javax.swing.JPanel jPanel_Content_;
    private javax.swing.JPanel jPanel_Main_;
    private javax.swing.JPanel jPanel_MenuBarSmall_;
    private javax.swing.JPanel jPanel_MenuBar_;
    private javax.swing.JPanel jPanel_StatusBar_;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane_Content_;
    // End of variables declaration//GEN-END:variables
}
