/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.venta;

import java.awt.Color;
import java.awt.Toolkit;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.util.Locale;

/**
 *
 * @author Freddy Camposeco <ankoku.fj@gmail.com> <www.stufs.rf.gd>
 */
public class CambioEfectivo extends javax.swing.JFrame {
    private final Locale locale = new Locale("es", "GT");
    private DecimalFormatSymbols dfs;
    private DecimalFormat df;
    private Double cambio = 0.0;

    private void showCambio (){
        jLabel_Cambio_.setText(df.format(Double.valueOf(cambio)));
        jLabel_Cambio_.revalidate();
        jLabel_Cambio_.repaint();
    }
    
    public void setCambio(Double cambio) {
        this.cambio = cambio;
        showCambio ();
    }
    
    private void settings(){
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource(gui.MainMenu.getIconDir())));
        dfs = new DecimalFormatSymbols(locale);
        dfs.setDecimalSeparator('.');
        dfs.setGroupingSeparator(',');
        df = new DecimalFormat("Q  ###,###,###,##0.00",dfs);
    }
    
    private void settingsPos(){
        setBackground(new Color (22,22,22,160));
    }
    
    public CambioEfectivo() {
        settings();
        initComponents();
        settingsPos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_Main_ = new javax.swing.JPanel();
        jLabel_Cambio_ = new javax.swing.JLabel();
        jLabel_Q_ = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cambio");
        setAlwaysOnTop(true);
        setMaximumSize(null);
        setMinimumSize(new java.awt.Dimension(555, 222));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(555, 222));
        setType(java.awt.Window.Type.POPUP);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel_Main_.setBackground(new java.awt.Color(204, 0, 0));
        jPanel_Main_.setMaximumSize(null);
        jPanel_Main_.setMinimumSize(new java.awt.Dimension(555, 222));
        jPanel_Main_.setOpaque(false);
        jPanel_Main_.setPreferredSize(new java.awt.Dimension(555, 222));
        jPanel_Main_.setLayout(new java.awt.BorderLayout());

        jLabel_Cambio_.setBackground(new java.awt.Color(255, 0, 102));
        jLabel_Cambio_.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel_Cambio_.setForeground(new java.awt.Color(0, 255, 0));
        jLabel_Cambio_.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Cambio_.setText("0.00");
        jPanel_Main_.add(jLabel_Cambio_, java.awt.BorderLayout.CENTER);

        jLabel_Q_.setBackground(new java.awt.Color(255, 0, 255));
        jLabel_Q_.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel_Q_.setForeground(new java.awt.Color(0, 255, 0));
        jLabel_Q_.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Q_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/core/resources/icons/moneyX96.png"))); // NOI18N
        jLabel_Q_.setMaximumSize(null);
        jLabel_Q_.setMinimumSize(new java.awt.Dimension(130, 130));
        jLabel_Q_.setPreferredSize(new java.awt.Dimension(130, 130));
        jPanel_Main_.add(jLabel_Q_, java.awt.BorderLayout.WEST);

        getContentPane().add(jPanel_Main_, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        dispose();
    }//GEN-LAST:event_formMouseClicked

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased
        dispose();
    }//GEN-LAST:event_formKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CambioEfectivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CambioEfectivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CambioEfectivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CambioEfectivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new CambioEfectivo().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel_Cambio_;
    private javax.swing.JLabel jLabel_Q_;
    private javax.swing.JPanel jPanel_Main_;
    // End of variables declaration//GEN-END:variables
}
