/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.almacen.compra;

import com.toedter.calendar.JDateChooser;
import core.database.Conexion;
import static java.awt.Frame.NORMAL;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alicer
 */
public class bar_matDisponible extends javax.swing.JFrame {

    private void cerrar() {

        String botones[] = {"Cerrar", "Cancelar"};
        int eleccion = JOptionPane.showOptionDialog(this, "¿Desea cerrar la aplicación?", "Título", 0, 0, null, botones, this);
        if (eleccion == JOptionPane.YES_OPTION) {
            dispose();
        } else if (eleccion == JOptionPane.NO_OPTION) {
        }
    }
    int ID_ARTICULO = 0;
    String NOMBRE_ARTICULO = null;
    Double ONZASPRODUCTO = 0.0;
    String RESULTADO = null;
    private Date date = new Date();

    public void tabla() {
        DefaultTableModel modelo = new DefaultTableModel();
        jtProductos.setModel(modelo);
        modelo.addColumn("id.");
        modelo.addColumn("Nombre");
        modelo.addColumn("cantidad");
        modelo.addColumn("ONZAS");
    }

    public void popuptable() {
        JPopupMenu popmenu = new JPopupMenu();
        JMenuItem menuitem = new JMenuItem("Eliminar", new ImageIcon(getClass().getResource("/core/resources/icons/eli.png")));
        menuitem.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                DefaultTableModel model = (DefaultTableModel) jtProductos.getModel();
                int a = jtProductos.getSelectedRow();
                if (a < 0) {
                    JOptionPane.showMessageDialog(null,
                            "Debe seleccionar una fila de la tabla");
                } else {
                    int confirmar = JOptionPane.showConfirmDialog(null,
                            "Esta seguro que desea quitar el producto? ");
                    if (JOptionPane.OK_OPTION == confirmar) {
                        model.removeRow(a);
                        JOptionPane.showMessageDialog(null, "Registro Eliminado");
                    }
                }
            }
        });

        popmenu.add(menuitem);

        jtProductos.setComponentPopupMenu(popmenu);
    }

    /**
     * Creates new form Factura_ingreso
     */
    public bar_matDisponible() {
        initComponents();
        tabla();
        popuptable();

//        try {
//            PreparedStatement ps = null;
//            ResultSet rs = null;
//            Conexion cone = new Conexion();
//            com.mysql.jdbc.Connection conn = (com.mysql.jdbc.Connection) cone.conectar();
//            DefaultTableModel modelo2 = new DefaultTableModel();
//            jtArticulos.setModel(modelo2);
//
//            String sql = "select id, nombre, stock, costo from materiaprima ";
//            ps = conn.prepareStatement(sql);
//            rs = ps.executeQuery();
//
//            ResultSetMetaData rsMd = (ResultSetMetaData) rs.getMetaData();
//            int cantidadColumnas = rsMd.getColumnCount();
//
//            modelo2.addColumn("id.");
//            modelo2.addColumn("Nombre");
//            modelo2.addColumn("Existencia");
//            modelo2.addColumn("Costo");
//
//            int[] anchos = {10, 30, 70, 70};
//            for (int i = 0; i < jtArticulos.getColumnCount(); i++) {
//                jtArticulos.getColumnModel().getColumn(i).setPreferredWidth(anchos[i]);
//            }
//
//            while (rs.next()) {
//                Object[] filas = new Object[cantidadColumnas];
//                for (int i = 0; i < cantidadColumnas; i++) {
//                    filas[i] = rs.getObject(i + 1);
//                }
//                modelo2.addRow(filas);
//            }
//
//        } catch (SQLException ex) {
//            System.err.println(ex.toString());
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtProductos = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtArticulos = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Salida de Almacén", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtProductos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtProductos);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 60, 644, 266));

        jtArticulos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtArticulos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Código", "Nombre", "Cantidad Existente", "Onzas"
            }
        ));
        jtArticulos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtArticulosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtArticulos);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 476, 266));

        jButton2.setText("Guardar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 340, 112, 42));

        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 112, 42));

        txtBuscar.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });
        jPanel3.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 240, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel9.setText("Buscar Artículo:");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 120, 30));

        jButton3.setText("Nuevo");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, 100, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 1190, 410));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1268, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Conexion cone = new Conexion();
        ResultSet rs = null;
        com.mysql.jdbc.Connection conn = (com.mysql.jdbc.Connection) cone.connect();
        PreparedStatement ps = null;

        int filas = jtProductos.getRowCount();
        System.out.println("filas jc " + filas);
        try {

            for (int row = 0; row < filas; row++) {

                int idMateria = (int) jtProductos.getValueAt(row, 0);
                String descripcion = (String) jtProductos.getValueAt(row, 1);
                int cant = (int) jtProductos.getValueAt(row, 2);
                Double onzas = (Double) jtProductos.getValueAt(row, 3);

                ps = conn.prepareStatement("INSERT INTO `salida_almacen` (`materiaprima_id`, `descripcion`, `cantidad`, `onzas`) VALUES (?,?,?,?)");
                ps.setInt(1, idMateria);
                ps.setString(2, descripcion);
                ps.setInt(3, cant);
                ps.setDouble(4, onzas);
                ps.execute();
                System.out.println("asdfasdf" + idMateria + " " + descripcion + " " + cant + " " + onzas);

                ps = conn.prepareStatement("update materiaprima SET `stock` =  `stock` - '" + cant + "' WHERE `id` = '" + idMateria + "'");
                ps.execute();

                ps = conn.prepareStatement("update materiaprima_cocina SET `stock` =  `stock` + '" + onzas + " ' WHERE `id` = '" + idMateria + "'");
                ps.execute();
                System.out.println("ejecutado update");
            }
            JOptionPane.showMessageDialog(null, "Ingresado Correctamente");
            tabla();
            limpiar();
        } catch (SQLException ex) {
            System.out.println("error mysql" + ex);

        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jtArticulosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtArticulosMouseClicked

        int Fila = jtArticulos.getSelectedRow();
        String codigo = jtArticulos.getValueAt(Fila, 0).toString();
        String nombre = jtArticulos.getValueAt(Fila, 1).toString();
        String ONZAS = jtArticulos.getValueAt(Fila, 3).toString();
        ID_ARTICULO = Integer.parseInt(codigo);
        NOMBRE_ARTICULO = nombre;
        ONZASPRODUCTO = Double.parseDouble(ONZAS);

        System.out.println("id " + ID_ARTICULO);
        System.out.println("Nombre: " + NOMBRE_ARTICULO);
        System.out.println("CA: " + ONZAS);
    }//GEN-LAST:event_jtArticulosMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String cant = JOptionPane.showInputDialog(null, "Ingrese la cantidad", "Ingreso de cantidad", JOptionPane.WARNING_MESSAGE);
        int cantidad = Integer.parseInt(cant);

//        String precioUnit = JOptionPane.showInputDialog(null, "Ingrese la cantidad", "Ingreso de cantidad", JOptionPane.WARNING_MESSAGE);
//        Double precioUni = Double.parseDouble(precioUnit);
        Double total = cantidad * ONZASPRODUCTO;

        DefaultTableModel modelo = (DefaultTableModel) jtProductos.getModel();
        Object[] fila = new Object[5];
        fila[0] = ID_ARTICULO;
        fila[1] = NOMBRE_ARTICULO;
        fila[2] = cantidad;
        fila[3] = total;
        modelo.addRow(fila);
//        jtProductos.setModel(modelo);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        cerrar();
    }//GEN-LAST:event_formWindowClosing

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        try {
            Conexion cone = new Conexion();
            com.mysql.jdbc.Connection conn = (com.mysql.jdbc.Connection) cone.connect();
            PreparedStatement ps = null;
            ResultSet rs = null;
            DefaultTableModel modelo = new DefaultTableModel();
            jtArticulos.setModel(modelo);

            String sql = "select id, nombre, stock, onzas from materiaprima where nombre LIKE '%" + txtBuscar.getText() + "%' order by(id) ";
            ps = conn.prepareStatement(sql);
            rs = ps.executeQuery();

            ResultSetMetaData rsMd = (ResultSetMetaData) rs.getMetaData();
            int cantidadColumnas = rsMd.getColumnCount();

            modelo.addColumn("Código.");
            modelo.addColumn("Nombre");
            modelo.addColumn("Existencia");
            modelo.addColumn("onzas");

            int[] anchos = {10, 150, 70, 70};
            for (int i = 0; i < jtArticulos.getColumnCount(); i++) {
                jtArticulos.getColumnModel().getColumn(i).setPreferredWidth(anchos[i]);
            }

            while (rs.next()) {
                Object[] filas = new Object[cantidadColumnas];
                for (int i = 0; i < cantidadColumnas; i++) {
                    filas[i] = rs.getObject(i + 1);
                }
                modelo.addRow(filas);
            }

        } catch (SQLException ex) {
            System.err.println(ex.toString());
        }
    }//GEN-LAST:event_txtBuscarKeyReleased

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        gui.almacen.RegistroLicores almacen = new gui.almacen.RegistroLicores(null, true);
        almacen.setVisible(true);

    }//GEN-LAST:event_jButton3ActionPerformed

    private void limpiar() {

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bar_matDisponible.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bar_matDisponible.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bar_matDisponible.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bar_matDisponible.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new bar_matDisponible().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jtArticulos;
    private javax.swing.JTable jtProductos;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
